export const filmdb = [
    {
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"1"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"2"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"3"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"4"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"5"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"6"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"7"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"8"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"9"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"10"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"11"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"12"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"13"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"14"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"15"
},
{
    country:"Antarctica state",
    director:"Evil dictator",
    duration: 666,
    year: "2256",
    description:"The evil dictator is destroying the earth",
    image:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    trailerLink:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    thumbnail:"https://img.freehat.cc/upload/iblock/7d1/Bez-imeni_143.jpg",
    nameRU:"Кровавый диктатор",
    nameEN:"Evil dictator",
    _id:"16"
},
];

export const filmdbSaved = [
    {
        country:"Small country",
        director:"Egor",
        duration: 103,
        year: "1987",
        description:"Egor conquers the world stage",
        image:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        trailerLink:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        thumbnail:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        nameRU:"Веселый Егор",
        nameEN:"Cheerful Egor",
        _id:"17"
    }, 
    {
        country:"Small country",
        director:"Egor",
        duration: 103,
        year: "1987",
        description:"Egor conquers the world stage",
        image:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        trailerLink:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        thumbnail:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        nameRU:"Веселый Егор",
        nameEN:"Cheerful Egor",
        _id:"18"
    }, 
    {
        country:"Small country",
        director:"Egor",
        duration: 103,
        year: "1987",
        description:"Egor conquers the world stage",
        image:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        trailerLink:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        thumbnail:"https://webpulse.imgsmail.ru/imgpreview?key=pulse_cabinet-file-2edf9edb-8669-408b-9324-54fdac590fce&mb=webpulse",
        nameRU:"Веселый Егор",
        nameEN:"Cheerful Egor",
        _id:"19"
    }, 
];